# Generated by Django 2.2.3 on 2019-07-10 03:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staticsites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('staticpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staticsites.StaticPageBase')),
                ('index', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staticsites.IndexPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('staticsites.staticpagebase',),
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('publish_on', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_relpath', models.CharField(default='imgs/news', max_length=250)),
                ('title', models.CharField(help_text='News Item Title', max_length=150)),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='news_newsitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('newspage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsPage')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='news_newsitem_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
