# Generated by Django 2.2.3 on 2019-07-07 14:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('index', 'index'), ('news', 'news')], editable=False, max_length=25, null=True)),
                ('filename', models.CharField(help_text='HTML Page filename', max_length=150)),
                ('relative_path', models.CharField(help_text='Relative Path from root index file where file exists', max_length=250)),
                ('template', models.TextField(help_text='Index template (in django template language format)')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='staticsites_staticpagebase_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('staticpagebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='staticsites.StaticPageBase')),
                ('newsitems_template_variablename', models.CharField(blank=True, help_text='Define if index template contains news items', max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('staticsites.staticpagebase',),
        ),
        migrations.CreateModel(
            name='StaticSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Descriptor for Site', max_length=150)),
                ('staging_bucket', models.CharField(help_text='S3 staging bucket name ', max_length=63, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('production_bucket', models.CharField(help_text='S3 production bucket name', max_length=63, validators=[django.core.validators.MinLengthValidator(limit_value=3)])),
                ('last_staging_sync_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_production_sync_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='staticsites_staticsite_created_by', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='staticsites_staticsite_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='staticpagebase',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staticsites.StaticSite'),
        ),
        migrations.AddField(
            model_name='staticpagebase',
            name='updated_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='staticsites_staticpagebase_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PageAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('css', 'css'), ('js', 'javascript'), ('img', 'image'), ('pdf', 'pdf')], help_text="Type of file ((('css', 'css'), ('js', 'javascript'), ('img', 'image'), ('pdf', 'pdf')))", max_length=15)),
                ('filename', models.CharField(help_text='Filename', max_length=150)),
                ('relative_path', models.CharField(help_text='Relative Path from root index file where file exists', max_length=250)),
                ('file_content', models.FileField(upload_to='')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='staticsites_pageasset_created_by', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staticsites.StaticPageBase')),
                ('updated_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='staticsites_pageasset_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
